### ISSUE TITLE
what is the command to get database from COSMIC

### ISSUE THREAD

**Issue by ypriverol** [nf-core/pgdb#3] opened 2021-02-09 09:28 UTC
Hi @husensofteng : 

@jgriss is interested to generate a database for the following cancer samples: 

https://cancer.sanger.ac.uk/cosmic/browse/tissue?hn=carcinoma&in=t&sh=Merkel_cell_carcinoma&sn=skin&ss=face

**Comment by jgriss** [comment] 2021-02-09 10:23
Thanks a lot for the help!

**Comment by husensofteng** [comment] 2021-02-09 15:20
I will get back to this once #4 and #5  are fixed.

**Comment by husensofteng** [comment] 2021-02-10 10:11
The command to generate a database only for mutations from Merkel_cell_carcinoma in cosmic:

`nextflow main.nf -profile docker  --ensembl_name homo_sapiens --cosmic true --add_reference false --cosmic_user_name your_cosmic_username --cosmic_password your_cosmic_pass --cosmic_cancer_type 'Merkel_cell_carcinoma'
`

**Comment by husensofteng** [comment] 2021-02-10 10:16
@jgriss could you please check it and remember to input the cosmic account login

**Comment by ypriverol** [comment] 2021-02-10 10:43
@husensofteng can you add also the cBioPortal part.

**Comment by husensofteng** [comment] 2021-02-10 11:09
For cbioPortal you need to know what cancer type you want, the command would be:

`nextflow main.nf -profile docker --ensembl_name homo_sapiens --cbioportal true --add_reference false --cbioportal_tissue_type 'cancer_type'
`

**Comment by jgriss** [comment] 2021-02-10 17:20
Hi @husensofteng @ypriverol 

Thanks a lot!!!

Fasta file was created without a problem. Now I have to wait to see how it affects the actual results. I'll keep you posted!

**Comment by husensofteng** [comment] 2021-03-12 14:15
I assume the issue is solved so I will close it, please feel free to re-open

**Closed as completed by husensofteng** 2021-03-12 14:15 UTC
Labels: enhancement, help wanted
